name: ðŸ› Bug Report
description: Use this template to report a bug
labels: [bug]
projects: NickAdvisor95/2
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **ONCE YOU ASSIGNED YOURSELF TO THE ISSUE:**
        > 1. That issue will be moved from `To Do` to `In Progress`
        > 2. The issue's `Start date` will be set to the current date
  - type: textarea
    attributes:
      label: Description
      description: |
        **CLEARLY DESCRIBE A BUG YOU ARE REPORTING, YOU CAN ADD PICTURES IF YOU WANT TO:**
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to fix the bug
      description: |
        **PROVIDE SUBTASKS TO FIX THE BUG,
        USE THE FOLLOWING FORMAT:**
        ```
        - [ ] First subtask (change the text as you want)
        - [ ] Second subtask
        - [ ] Third subtask

        ...
        ```
        **TO DO THAT, SIMPLY CLICK ON THE `Task list` BUTTON:**
        ![](https://github.com/alechkos/vzou/assets/93551621/5798c8a3-efc9-4ed9-ba18-da93cbebd46b)
    validations:
      required: false